### ISSUE TITLE
Issue with micro_ros_uart demo

### ISSUE THREAD

**Issue by Jackogip** [micro-ROS/micro_ros_renesas_demos#123]
## Issue

- Hardware description: EKRA6M5
- RTOS: Bare-metal 
- Installation type: micro_ros_uart demo
- Version or commit hash: ROS2 humble

#### Steps to reproduce the issue
Run the standard UART demo connected to Ubuntu 22.04 with the UART micro-ROS Agent

#### Expected behavior
That the micro-ROS agent would continually publish the incremented msg.data

#### Actual behavior
The micro-ROS agent only publishes:
![image](https://github.com/micro-ROS/micro_ros_renesas_demos/assets/105869653/18496717-6e71-4298-ad17-e6c5019405cf)

After that it seems to stop publishing data.

#### Additional information
When there is no UART connection when the micro_ros_uart demo projects starts it will get stuck in the:
`BSP_ATTRIBUTE_STACKLESS void bsp_prv_software_delay_loop (__attribute__((unused)) uint32_t loop_cnt)`

**Comment by Acuadros95** [comment]
Did you check if the data is being published on a ROS 2 terminal?

The agent log of your image looks correct. To view logs of actual data publications, you will need to launch the Agent in debug mode, adding the flag `-v6`.

> When there is no UART connection when the micro_ros_uart demo projects starts it will get stuck in the:

The demo is just a simple publisher, which expects the Agent to be present on its initialization. Agent disconnections can be handled with the ping feature, check this tutorial for more details: [4.3. Reconnections and liveliness](https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/handle_reconnections/handle_reconnections.html)

**Comment by Jackogip** [comment]
Yes, my mistake the messages are there.

> The demo is just a simple publisher, which expects the Agent to be present on its initialization. Agent disconnections can be handled with the ping feature, check this tutorial for more details: [4.3. Reconnections and liveliness](https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/handle_reconnections/handle_reconnections.html) <

Ok thanks
