### ISSUE TITLE
EK RA6M5 not listed in /dev/serial/by-id/ when connected to laptop

### ISSUE THREAD

**Issue by Srichitra-S** [micro-ROS/micro_ros_renesas_demos#134]
## EK RA6M5 not listed in /dev/serial/by-id/ when connected to laptop

- Hardware description: EK RA6M5 
 <!RTOS: -- RTOS where you are using micro-ROS -->
 <!Installation type: -- micro_ros_setup, modules, etc  -->
<!Version or commit hash: humble 

#### Steps to reproduce the issue

Was following the steps to run the microros demo for Serial micro-ROS Agent. 
But the board port is not visible when using the command ` ls /dev/serial/by-id/`
 

#### Expected behavior
the board port is listed 
#### Actual behavior
the directory not found
#### Additional information
Also tested the udp microros agent, but the app doesnt run successfully on the board.

**Comment by pablogs9** [comment]
Was the board correctly flashed?

**Comment by Srichitra-S** [comment]
> Was the board correctly flashed?

Yes. Flashed using e2studio.

**Comment by pablogs9** [comment]
There are 3 micro-USB on board, could you confirm that any of them mount a serial device?

**Comment by pablogs9** [comment]
Also:
- which example are you using? 
- version of Renesas e2studio?
- version of FSP?

**Comment by Srichitra-S** [comment]
> Also:
> 
>     * which example are you using?
Serial micro-ROS Agent
> 
>     * version of Renesas e2studio?
e2studio_v2023-04
> 
>     * version of FSP?
FSP v4.4.0

**Comment by Srichitra-S** [comment]
> There are 3 micro-USB on board, could you confirm that any of them mount a serial device?

i connected the full speed usb and the debug usb port

**Comment by pablogs9** [comment]
The UDPv4 example will communicate via UDP, there is not serial port communication for micro-ROS in this example.

Closing as solved.

**Comment by Srichitra-S** [comment]
> The UDPv4 example will communicate via UDP, there is not serial port communication for micro-ROS in this example.
> 
> Closing as solved.

Sorry @pablogs9 
Serial micro-ROS Agent was the example used

**Comment by pablogs9** [comment]
Which of these examples are you using: https://github.com/micro-ROS/micro_ros_renesas_demos/tree/iron/Boards/EK_RA6M5 ?

**Comment by Srichitra-S** [comment]
> Which of these examples are you using: https://github.com/micro-ROS/micro_ros_renesas_demos/tree/iron/Boards/EK_RA6M5 ?

micro_ros_usb
