### ISSUE TITLE
pinging takes too long when EKRA6M5  is connected to the laptop via ethernet

### ISSUE THREAD

**Issue by Srichitra-S** [micro-ROS/micro_ros_renesas_demos#135]
## pinging takes too long when EKRA6M5  is connected to the laptop via ethernet

- Hardware description: EKRA6M5 
- Installation type: UDPv4 micro-ROS Agent 

#### Steps to reproduce the issue
Connected the board to laptop via ethernet cable.
Tried to ping the IP address.  

![MicrosoftTeams-image (1)](https://github.com/micro-ROS/micro_ros_renesas_demos/assets/62196293/06f458b6-2fe2-45bf-b04a-e0f81f81d065)

**Comment by pablogs9** [comment]
Not related to micro-ROS.

**Comment by Srichitra-S** [comment]
The ping works but the micrros agent doesnt run and rostopics are not listed. @pablogs9
