### ISSUE TITLE
EK RA6M5 not listed in COM port in Windows 10 .

### ISSUE THREAD

**Issue by Srichitra-S** [micro-ROS/micro_ros_renesas_demos#136]
## EK RA6M5 not listed in COM port in Windows 10 .

- Hardware description: EKRA6M5 

#### Steps to reproduce the issue

Followed the quick start guide to EKRA6M5.
The device isnt listed in any of the com ports.
USB serial drivers are updated in the system.

**Comment by pablogs9** [comment]
Not supported in Windows: https://github.com/micro-ROS/micro_ros_renesas2estudio_component#requirements

Maybe repeated: https://github.com/micro-ROS/micro_ros_renesas_demos/issues/134

Could you confirm that it is the same issue?

**Comment by Srichitra-S** [comment]
No. I was not running any examples. Just following the quick start guide. The [steps mentioned in 4.2](https://www.renesas.com/us/en/document/qsg/ek-ra6m5-quick-start-guide?r=1494266) is to see the ports in device manager.

**Comment by pablogs9** [comment]
Which example are you running?

**Comment by Srichitra-S** [comment]
> No. I was not running any examples. Just following the quick start guide. The [steps mentioned in 4.2](https://www.renesas.com/us/en/document/qsg/ek-ra6m5-quick-start-guide?r=1494266) is to see the ports in device manager.

i am running this

**Comment by pablogs9** [comment]
> I was not running any examples.


Not related to micro-ROS
