### ISSUE TITLE
Would it be possible to run the middleware on the RA8M1

### ISSUE THREAD

**Issue by Imeguras** [micro-ROS/micro_ros_renesas_demos#140]
## Issue template

- Hardware description: RA8M1
- RTOS: Azure
- Installation type: N/A
- Version or commit hash: humble

So was it tested? I've used the ra6m5 but noticed some performance issues, i was hoping the increased clock speed and benchmark tests of the ra8m1 would improve the results

**Comment by pablogs9** [comment]
Hello @Imeguras, I have looked at the RA8M1 features and it seems that there shall be no problem running micro-ROS there.

Unfortunately, we do not have support for those boards, although it shall be not so difficult to reuse the [micro-ROS component for e2studio](https://github.com/micro-ROS/micro_ros_renesas2estudio_component) with some modifications to target this new board.

Please don't hesitate to contribute back if your port is successful.

**Comment by Imeguras** [comment]
> Please don't hesitate to contribute back if your port is successful.

Well it seems that you're everywhere :)
I was successful in making micro ros work, although i used my code as im more familiar with its quirks. I will be making a simpler version with the template thats been used and hopefully contribute to this project as i find it very interesting, also i used threadX for it, as im more familiar with it
