### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by jpeyron** [micro-ROS/micro_ros_renesas_demos#73]
Hello,

I am using an EK RA6M5 Renesas dev board with e2 studios +FSP installed on both a windows and Ubuntu 20.04 linux pc as well as a Ubuntu 20.04 linux Virtual Box. I have tried using different toolchain versions to see it this would resolve the issue with no change. After attempting to build any of the project i get path warning and errors. If i get the project to build it does not create an elf or hex file. I have attached a copy of the console and problem text from e2 studios

thank you,

Jon Peyron

[errors_2a.odt](https://github.com/micro-ROS/micro_ros_renesas_demos/files/8833141/errors_2a.odt)

**Comment by pablogs9** [comment]
Hello, could you detail your build procedure and paste the log here?

**Comment by jpeyron** [comment]
I used the 3.7.0 release from here [https://github.com/renesas/fsp/releases](url).
I downloaded the Renesas micro-ROS demo from [here:](https://github.com/micro-ROS/micro_ros_renesas_demos)
after launching e2 studios I select add an existing project and add all or just the usb demo with no difference in build issue. I then select build and the above attached file from previous post has both the problems and console text. I have also added the micro_ros_usb.build.log below. I have added multiple arm toolchains and used each with no difference in build outcome.
![image](https://user-images.githubusercontent.com/12866456/172191165-19734ae7-44fd-4440-811f-400afc9518e0.png)

let me know if there is anything else i can detail or add here.

thank you,

Jon



[micro_ros_usb.build.zip](https://github.com/micro-ROS/micro_ros_renesas_demos/files/8845416/micro_ros_usb.build.zip)

**Comment by pablogs9** [comment]
Any update on this @Acuadros95 ?

**Comment by Acuadros95** [comment]
@jpeyron Sorry for the delay!

>  If the i have the usb connected to the Full speed port on the Renesas dev board it does create a serial port

That is the expected behavior, you should use the Full speed USB port as micro-ROS serial transport.
Did you try to use the agent with this port?
