### ISSUE TITLE
Demo 3 Parameter Server not working

### ISSUE THREAD

**Issue by Jackogip** [micro-ROS/micro_ros_renesas_demos#85]
## Issue template

- Hardware description: EK-RA6M5
- RTOS: Bare metal
- Installation type: demo3
- Version or commit hash: ros2 Foxy

#### Steps to reproduce the issue
- Run the default demo3 project from e2 studio
- from Linux terminal run: `$ros2 param list`

#### Expected behavior
- /my_renesas_node:
   blue
   green
   red
#### Actual behavior
Command times out without returning anything.

#### Additional information
The node is showing up as /my_renesas_node and the code is executing fine and getting to the while loop.

When running `ros2 node info /my_renesas_node --` I get the following:

```
/my_renesas_node
  Subscribers:

  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
  Service Servers:
    /my_renesas_node/get_parameters: rcl_interfaces/srv/GetParameters
  Service Clients:

  Action Servers:

  Action Clients:
```

**Comment by Acuadros95** [comment]
The memory configuration file was missing: [detail](https://github.com/micro-ROS/micro_ros_renesas_demos/blob/demo3/micro_ros_usb/app_colcon.meta).

I have updated the demo branch with the correct configuration and also upgrade it to Humble.
This adds improvements in the parameter server callback, check them out in the micro-ROS app file.

For more details on the parameter server update, you can check this documentation: [link](https://micro.ros.org/docs/tutorials/programming_rcl_rclc/parameters/). Focus on the `micro-ROS Humble` section.

**Comment by Jackogip** [comment]
@Acuadros95 
When running this project now I get: 
'RCLC_EXECUTOR_PARAMETER_SERVER_HANDLES' undeclared (first use of this function)

This is odd since the rclc_parameter.h is included and RCLC_EXECUTOR_PARAMETER_SERVER_HANDLES is there.

Any ideas on what the issue might be?

**Comment by Acuadros95** [comment]
Just tested it locally and it builds, some ideas:
- Check that your  `micro_ros_renesas2estudio_component` submodule is updated to the expected commit ([detail](https://github.com/micro-ROS/micro_ros_renesas_demos/tree/demo3/micro_ros_usb)).
- Rebuild micro-ROS: Delete the `micro_ros_renesas2estudio_component/libmicroros` folder and build your project.
- Clean the project and rebuild.
- Make sure that your `rclc_parameter.h` is equal to [this one](https://github.com/ros2/rclc/blob/humble/rclc_parameter/include/rclc_parameter/rclc_parameter.h).

**Comment by Jackogip** [comment]
Thanks.

I followed these steps but the `rclc_parameter.h ` file still looked different so I manually replaced it which then worked (complied and param list shows up)

However, LEDs are not getting set when setting it from ROS CL.

A few thing which I was thinking:
- I'm currently running FSP 3.6 vs 3.5
- I'm using foxy not sure what you tested yours on? humble I guess? I assume the `libmicroros` files a generated based on the version of ros which is being used

**Comment by Jackogip** [comment]
Thanks this worked. 

I was working from an older version - sorry for that :)

**Comment by Jackogip** [comment]
Hi @Acuadros95 

I'm trying to use the UART version of demo 3 now and I'm having a similar issue when compiling I'm getting the following errors at the 'create executor':

`RCLC_EXECUTOR_PARAMETER_SERVER_HANDLES' undeclared (first use in this function)`
&
`error: passing argument 3 of 'rclc_executor_add_parameter_server' from incompatible pointer type [-Werror=incompatible-pointer-types]`

I've pulled the latest foxy files and tried to go through the steps above but still having this issue. 

Any ideas?

**Comment by Acuadros95** [comment]
> I've pulled the latest foxy files and tried to go through the steps above but still having this issue.

You should use the commit that is on the repository. 

This new paremeter API works targets **micro-ROS Humble**, but you should not encounter problems communicating with ROS2 foxy.
